### ISSUE TITLE
Fail to run on ubuntu 16.04, tf 1.8, keras 2.1.5

### ISSUE THREAD

**Issue by li3ro** [hashemsellat/Video-Anomaly-Detection#1]
not sure why it fails to run. would love your assistance

KeyError                                  Traceback (most recent call last)
<ipython-input-14-3f393ad04e6a> in <module>()
----> 1 evaluate()

<ipython-input-12-01d0ff0639bf> in evaluate()
      2 
      3 def evaluate():
----> 4     model = get_model(False)
      5     print("got model")
      6     test = get_single_test()

<ipython-input-10-64e7653da206> in get_model(reload_model)
     11     """
     12     if not reload_model:
---> 13         return load_model(Config.MODEL_PATH,custom_objects={'LayerNormalization': LayerNormalization})
     14     training_set = get_training_set()
     15     training_set = np.array(training_set)

/home/liero/anaconda3/envs/py36/lib/python3.6/site-packages/keras/models.py in load_model(filepath, custom_objects, compile)
    241             raise ValueError('No model found in config file.')
    242         model_config = json.loads(model_config.decode('utf-8'))
--> 243         model = model_from_config(model_config, custom_objects=custom_objects)
    244 
    245         # set weights

/home/liero/anaconda3/envs/py36/lib/python3.6/site-packages/keras/models.py in model_from_config(config, custom_objects)
    315                         'Maybe you meant to use '
    316                         '`Sequential.from_config(config)`?')
--> 317     return layer_module.deserialize(config, custom_objects=custom_objects)
    318 
    319 

/home/liero/anaconda3/envs/py36/lib/python3.6/site-packages/keras/layers/__init__.py in deserialize(config, custom_objects)
     53                                     module_objects=globs,
     54                                     custom_objects=custom_objects,
---> 55                                     printable_module_name='layer')

/home/liero/anaconda3/envs/py36/lib/python3.6/site-packages/keras/utils/generic_utils.py in deserialize_keras_object(identifier, module_objects, custom_objects, printable_module_name)
    142                 return cls.from_config(config['config'],
    143                                        custom_objects=dict(list(_GLOBAL_CUSTOM_OBJECTS.items()) +
--> 144                                                            list(custom_objects.items())))
    145             with CustomObjectScope(custom_objects):
    146                 return cls.from_config(config['config'])

/home/liero/anaconda3/envs/py36/lib/python3.6/site-packages/keras/models.py in from_config(cls, config, custom_objects)
   1365     @classmethod
   1366     def from_config(cls, config, custom_objects=None):
-> 1367         if 'class_name' not in config[0] or config[0]['class_name'] == 'Merge':
   1368             return cls.legacy_from_config(config)
   1369 

KeyError: 0

**Comment by hashemsellat** [comment]
Just set the model_path in Config to "model.hdm5" path, or reload the model by calling get_model(true)

**Comment by li3ro** [comment]
Thank you so much for your quick reply and assistance!!

EDIT1:
It works. This is is closed :)
