### ISSUE TITLE
OOM on "slow" GPU/CPU setup

### ISSUE THREAD

**Issue by li3ro** [hashemsellat/Video-Anomaly-Detection#2]
Hi, as the title suggest I'm getting an OOM exception, I think while trying to load the model.
Tried to lower the BATCH_SIZE=1, EPOCHS=1 , getting the same error.
Is there a way to work with lower memory footprint?
my setup is nVidia GT 730 (2gb mem) with 8 cores amd CPU / 16gb ram

StackTrace:

Layer (type)                 Output Shape              Param #   
time_distributed_1 (TimeDist (None, 10, 64, 64, 128)   15616     
layer_normalization_1 (Layer (None, 10, 64, 64, 128)   256       
time_distributed_2 (TimeDist (None, 10, 32, 32, 64)    204864    
layer_normalization_2 (Layer (None, 10, 32, 32, 64)    128       
conv_lst_m2d_1 (ConvLSTM2D)  (None, 10, 32, 32, 64)    295168    
layer_normalization_3 (Layer (None, 10, 32, 32, 64)    128       
conv_lst_m2d_2 (ConvLSTM2D)  (None, 10, 32, 32, 32)    110720    
layer_normalization_4 (Layer (None, 10, 32, 32, 32)    64        
conv_lst_m2d_3 (ConvLSTM2D)  (None, 10, 32, 32, 64)    221440    
layer_normalization_5 (Layer (None, 10, 32, 32, 64)    128       
time_distributed_3 (TimeDist (None, 10, 64, 64, 64)    102464    
layer_normalization_6 (Layer (None, 10, 64, 64, 64)    128       
time_distributed_4 (TimeDist (None, 10, 256, 256, 128) 991360    
layer_normalization_7 (Layer (None, 10, 256, 256, 128) 256       
time_distributed_5 (TimeDist (None, 10, 256, 256, 1)   15489     
Total params: 1,958,209
Trainable params: 1,958,209
Non-trainable params: 0

None
WARNING:tensorflow:Variable *= will be deprecated. Use variable.assign_mul if you want assignment to the variable value or 'x = x * y' if you want a new python Tensor object.
Epoch 1/3

ResourceExhaustedError                    Traceback (most recent call last)
/home/liero/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/client/session.py in _do_call(self, fn, *args)
   1321     try:
-> 1322       return fn(*args)
   1323     except errors.OpError as e:

/home/liero/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/client/session.py in _run_fn(feed_dict, fetch_list, target_list, options, run_metadata)
   1306       return self._call_tf_sessionrun(
-> 1307           options, feed_dict, fetch_list, target_list, run_metadata)
   1308 

/home/liero/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/client/session.py in _call_tf_sessionrun(self, options, feed_dict, fetch_list, target_list, run_metadata)
   1408           self._session, options, feed_dict, fetch_list, target_list,
-> 1409           run_metadata)
   1410     else:

ResourceExhaustedError: OOM when allocating tensor with shape[40,128,256,256] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[Node: time_distributed_4/conv2d_transpose = Conv2DBackpropInput[T=DT_FLOAT, _class=["loc:@training/Adam/gradients/time_distributed_4/conv2d_transpose_grad/Conv2D"], data_format="NCHW", dilations=[1, 1, 1, 1], padding="SAME", strides=[1, 1, 4, 4], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](time_distributed_4/conv2d_transpose-0-VecPermuteNHWCToNCHW-LayoutOptimizer/_577, time_distributed_4/kernel/read, time_distributed_4/conv2d_transpose-2-TransposeNHWCToNCHW-LayoutOptimizer)]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

	 [[Node: training/Adam/gradients/time_distributed_4/Reshape_1_grad/Shape/_633 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_3347_training/Adam/gradients/time_distributed_4/Reshape_1_grad/Shape", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

During handling of the above exception, another exception occurred:

ResourceExhaustedError                    Traceback (most recent call last)
<ipython-input-6-a01d9c651e3c> in <module>()
      1 #get_model(True)
----> 2 evaluate()

<ipython-input-5-f8e4de096eaf> in evaluate()
      2 
      3 def evaluate():
----> 4     model = get_model(True)
      5     print("got model")
      6     test = get_single_test()

<ipython-input-3-64e7653da206> in get_model(reload_model)
     36     seq.compile(loss='mse', optimizer=keras.optimizers.Adam(lr=1e-4, decay=1e-5, epsilon=1e-6))
     37     seq.fit(training_set, training_set,
---> 38             batch_size=Config.BATCH_SIZE, epochs=Config.EPOCHS, shuffle=False)
     39     seq.save(Config.MODEL_PATH)
     40     return seq

/home/liero/anaconda3/envs/py36/lib/python3.6/site-packages/keras/models.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, **kwargs)
    961                               initial_epoch=initial_epoch,
    962                               steps_per_epoch=steps_per_epoch,
--> 963                               validation_steps=validation_steps)
    964 
    965     def evaluate(self, x=None, y=None,

/home/liero/anaconda3/envs/py36/lib/python3.6/site-packages/keras/engine/training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, **kwargs)
   1703                               initial_epoch=initial_epoch,
   1704                               steps_per_epoch=steps_per_epoch,
-> 1705                               validation_steps=validation_steps)
   1706 
   1707     def evaluate(self, x=None, y=None,

/home/liero/anaconda3/envs/py36/lib/python3.6/site-packages/keras/engine/training.py in _fit_loop(self, f, ins, out_labels, batch_size, epochs, verbose, callbacks, val_f, val_ins, shuffle, callback_metrics, initial_epoch, steps_per_epoch, validation_steps)
   1233                         ins_batch[i] = ins_batch[i].toarray()
   1234 
-> 1235                     outs = f(ins_batch)
   1236                     if not isinstance(outs, list):
   1237                         outs = [outs]

/home/liero/anaconda3/envs/py36/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py in __call__(self, inputs)
   2476         session = get_session()
   2477         updated = session.run(fetches=fetches, feed_dict=feed_dict,
-> 2478                               **self.session_kwargs)
   2479         return updated[:len(self.outputs)]
   2480 

/home/liero/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/client/session.py in run(self, fetches, feed_dict, options, run_metadata)
    898     try:
    899       result = self._run(None, fetches, feed_dict, options_ptr,
--> 900                          run_metadata_ptr)
    901       if run_metadata:
    902         proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)

/home/liero/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/client/session.py in _run(self, handle, fetches, feed_dict, options, run_metadata)
   1133     if final_fetches or final_targets or (handle and feed_dict_tensor):
   1134       results = self._do_run(handle, final_targets, final_fetches,
-> 1135                              feed_dict_tensor, options, run_metadata)
   1136     else:
   1137       results = []

/home/liero/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/client/session.py in _do_run(self, handle, target_list, fetch_list, feed_dict, options, run_metadata)
   1314     if handle is None:
   1315       return self._do_call(_run_fn, feeds, fetches, targets, options,
-> 1316                            run_metadata)
   1317     else:
   1318       return self._do_call(_prun_fn, handle, feeds, fetches)

/home/liero/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/client/session.py in _do_call(self, fn, *args)
   1333         except KeyError:
   1334           pass
-> 1335       raise type(e)(node_def, op, message)
   1336 
   1337   def _extend_graph(self):

ResourceExhaustedError: OOM when allocating tensor with shape[40,128,256,256] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[Node: time_distributed_4/conv2d_transpose = Conv2DBackpropInput[T=DT_FLOAT, _class=["loc:@training/Adam/gradients/time_distributed_4/conv2d_transpose_grad/Conv2D"], data_format="NCHW", dilations=[1, 1, 1, 1], padding="SAME", strides=[1, 1, 4, 4], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](time_distributed_4/conv2d_transpose-0-VecPermuteNHWCToNCHW-LayoutOptimizer/_577, time_distributed_4/kernel/read, time_distributed_4/conv2d_transpose-2-TransposeNHWCToNCHW-LayoutOptimizer)]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

	 [[Node: training/Adam/gradients/time_distributed_4/Reshape_1_grad/Shape/_633 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_3347_training/Adam/gradients/time_distributed_4/Reshape_1_grad/Shape", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

Caused by op 'time_distributed_4/conv2d_transpose', defined at:
  File "/home/liero/anaconda3/envs/py36/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/liero/anaconda3/envs/py36/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/liero/anaconda3/envs/py36/lib/python3.6/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/home/liero/anaconda3/envs/py36/lib/python3.6/site-packages/traitlets/config/application.py", line 664, in launch_instance
    app.start()
  File "/home/liero/anaconda3/envs/py36/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 563, in start
    self.io_loop.start()
  File "/home/liero/anaconda3/envs/py36/lib/python3.6/site-packages/tornado/ioloop.py", line 832, in start
    self._run_callback(self._callbacks.popleft())
  File "/home/liero/anaconda3/envs/py36/lib/python3.6/site-packages/tornado/ioloop.py", line 605, in _run_callback
    ret = callback()
  File "/home/liero/anaconda3/envs/py36/lib/python3.6/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/liero/anaconda3/envs/py36/lib/python3.6/site-packages/tornado/gen.py", line 1152, in inner
    self.run()
  File "/home/liero/anaconda3/envs/py36/lib/python3.6/site-packages/tornado/gen.py", line 1069, in run
    yielded = self.gen.send(value)
  File "/home/liero/anaconda3/envs/py36/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 365, in process_one
    yield gen.maybe_future(dispatch(*args))
  File "/home/liero/anaconda3/envs/py36/lib/python3.6/site-packages/tornado/gen.py", line 307, in wrapper
    yielded = next(result)
  File "/home/liero/anaconda3/envs/py36/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 272, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "/home/liero/anaconda3/envs/py36/lib/python3.6/site-packages/tornado/gen.py", line 307, in wrapper
    yielded = next(result)
  File "/home/liero/anaconda3/envs/py36/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 542, in execute_request
    user_expressions, allow_stdin,
  File "/home/liero/anaconda3/envs/py36/lib/python3.6/site-packages/tornado/gen.py", line 307, in wrapper
    yielded = next(result)
  File "/home/liero/anaconda3/envs/py36/lib/python3.6/site-packages/ipykernel/ipkernel.py", line 294, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/home/liero/anaconda3/envs/py36/lib/python3.6/site-packages/ipykernel/zmqshell.py", line 536, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/home/liero/anaconda3/envs/py36/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2718, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/home/liero/anaconda3/envs/py36/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2828, in run_ast_nodes
    if self.run_code(code, result):
  File "/home/liero/anaconda3/envs/py36/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2882, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-6-a01d9c651e3c>", line 2, in <module>
    evaluate()
  File "<ipython-input-5-f8e4de096eaf>", line 4, in evaluate
    model = get_model(True)
  File "<ipython-input-3-64e7653da206>", line 32, in get_model
    seq.add(TimeDistributed(Conv2DTranspose(128, (11, 11), strides=4, padding="same")))
  File "/home/liero/anaconda3/envs/py36/lib/python3.6/site-packages/keras/models.py", line 492, in add
    output_tensor = layer(self.outputs[0])
  File "/home/liero/anaconda3/envs/py36/lib/python3.6/site-packages/keras/engine/topology.py", line 619, in __call__
    output = self.call(inputs, **kwargs)
  File "/home/liero/anaconda3/envs/py36/lib/python3.6/site-packages/keras/layers/wrappers.py", line 211, in call
    y = self.layer.call(inputs, **kwargs)
  File "/home/liero/anaconda3/envs/py36/lib/python3.6/site-packages/keras/layers/convolutional.py", line 778, in call
    data_format=self.data_format)
  File "/home/liero/anaconda3/envs/py36/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 3388, in conv2d_transpose
    data_format=tf_data_format)
  File "/home/liero/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 1254, in conv2d_transpose
    name=name)
  File "/home/liero/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 1228, in conv2d_backprop_input
    dilations=dilations, name=name)
  File "/home/liero/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/liero/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3392, in create_op
    op_def=op_def)
  File "/home/liero/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1718, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[40,128,256,256] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[Node: time_distributed_4/conv2d_transpose = Conv2DBackpropInput[T=DT_FLOAT, _class=["loc:@training/Adam/gradients/time_distributed_4/conv2d_transpose_grad/Conv2D"], data_format="NCHW", dilations=[1, 1, 1, 1], padding="SAME", strides=[1, 1, 4, 4], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](time_distributed_4/conv2d_transpose-0-VecPermuteNHWCToNCHW-LayoutOptimizer/_577, time_distributed_4/kernel/read, time_distributed_4/conv2d_transpose-2-TransposeNHWCToNCHW-LayoutOptimizer)]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

	 [[Node: training/Adam/gradients/time_distributed_4/Reshape_1_grad/Shape/_633 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_3347_training/Adam/gradients/time_distributed_4/Reshape_1_grad/Shape", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

**Comment by hashemsellat** [comment]
As mentioned in the article, use [Data Generator](https://stanford.edu/~shervine/blog/keras-how-to-generate-data-on-the-fly).

**Comment by li3ro** [comment]
Thanks! I will try it :)
