### ISSUE TITLE
Error in get_clips_by_stride

### ISSUE THREAD

**Issue by huikang** [hashemsellat/Video-Anomaly-Detection#6]
The for loop of `get_clips_by_stride` in https://github.com/hashemsellat/Video-Anomaly-Detection/blob/master/notebooks/lstmautoencoder/lstmautoencoder.ipynb seems incorrect.

After calling the `get_clips_by_stride`, it seems that all clips have the example same data.

I guess the problem is caused by theses lines `clip[cnt, :, :, 0] = frames_list[I], clips.append(clip)`, which adds a reference of clip to clips. Therefore, in the subsequence iteration, clip is kept being overwritten.

**Comment by hashemsellat** [comment]
Fixed.
